// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNpev2Z2Qy9Uw54wDtpmA9iLx_ZvvS9_E',
    appId: '1:467669188504:web:935d5b405e526cd067f5ed',
    messagingSenderId: '467669188504',
    projectId: 'flutterdb-6bfd1',
    authDomain: 'flutterdb-6bfd1.firebaseapp.com',
    storageBucket: 'flutterdb-6bfd1.firebasestorage.app',
    measurementId: 'G-SZP9VS3EGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4W5nVQYupY5uBtewVtcbepRtLnuN-7bw',
    appId: '1:467669188504:android:9a38d4bc0f28473867f5ed',
    messagingSenderId: '467669188504',
    projectId: 'flutterdb-6bfd1',
    storageBucket: 'flutterdb-6bfd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZjUdVx91cnN-RlN5qLcNq0-aDR_8i2nc',
    appId: '1:467669188504:ios:7159ec12fe0de9d667f5ed',
    messagingSenderId: '467669188504',
    projectId: 'flutterdb-6bfd1',
    storageBucket: 'flutterdb-6bfd1.firebasestorage.app',
    iosBundleId: 'com.example.babysitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZjUdVx91cnN-RlN5qLcNq0-aDR_8i2nc',
    appId: '1:467669188504:ios:7159ec12fe0de9d667f5ed',
    messagingSenderId: '467669188504',
    projectId: 'flutterdb-6bfd1',
    storageBucket: 'flutterdb-6bfd1.firebasestorage.app',
    iosBundleId: 'com.example.babysitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNpev2Z2Qy9Uw54wDtpmA9iLx_ZvvS9_E',
    appId: '1:467669188504:web:c0472f8a8ad45a5e67f5ed',
    messagingSenderId: '467669188504',
    projectId: 'flutterdb-6bfd1',
    authDomain: 'flutterdb-6bfd1.firebaseapp.com',
    storageBucket: 'flutterdb-6bfd1.firebasestorage.app',
    measurementId: 'G-E50ZDD9RM8',
  );
}
